version: '3'
services:
  postgres:
    container_name: plays-data-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  # blockchain:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: plays-data-blockchain
  #   environment:
  #     - PORT=3000
  #     - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/postgres
  #     - IS_MAINNET=${IS_MAINNET}
  #     - API_KEY=${API_KEY}
  #     - ANALYTICS_SERVICE_BASE_URL=${ANALYTICS_SERVICE_BASE_URL}
  #   ports:
  #     - '${PORT}:3000'
  #   depends_on:
  #     - postgres
volumes:
  postgres-data:
